Add low tanimoto check in routes.py. Display warning for tanimoto und…
sandboxnu/cheminformatics pull request #87
Opened 2020-03-28 02:55 UTC by klu17

…er .6 in cluster.html. #83

2020-03-29 14:04 UTC, aislinblack requested changes
I would prefer if it warned the user BEFORE they submit the coefficient.

2020-04-01 23:48 UTC, aislinblack requested changes
Just a couple changes and then you should be good to go!

2020-04-01 23:48 UTC, aislinblack commented on app/routes.py
> +from flask import render_template, request, session, flash
do we still need to import flask?

2020-04-01 23:48 UTC, aislinblack commented on app/routes.py
> +  low_tanimoto_warning = False
this doesn't seem needed anymore

2020-04-02 19:23 UTC, klu17 commented on app/routes.py
> +from flask import render_template, request, session, flash
I will remove this.

2020-04-02 19:23 UTC, klu17 commented on app/routes.py
> +  low_tanimoto_warning = False
Will remove this too.

2020-04-02 22:02 UTC, aislinblack requested changes

2020-04-02 22:02 UTC, aislinblack commented on app/templates/pains_verify_and_coefficient_use.html
> +            console.log(tanimoto);
maybe get rid of the console.log

2020-04-02 22:11 UTC, aislinblack approved these changes

2020-04-02 22:14 UTC, merged